services:
  postgres:
    image: postgres:15-alpine
    container_name: zk-auth-postgres
    environment:
      POSTGRES_DB: zkauth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 5656
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zk-auth-network

volumes:
  postgres_data:

networks:
  zk-auth-network:
    driver: bridge